{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45895,
          "sha512": "fa12a2d4b12a8e39a60f22f772da417fe23f16127edc08d6db7d92e642c965bd5b8634d3a0c963cc97bd4eb295990c8a4fba02929b7657a202c50fa7c93ec093",
          "sha256": "a43b1fb23732a1cb8707aa6801b42ed53aab7cc726a3aa6007175b428d238215",
          "sha1": "3320231d01f3b2acf6975a57dff8e61589ee072a",
          "md5": "d8b3b15afbc92254370f5a34829f665c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45895,
          "sha512": "fa12a2d4b12a8e39a60f22f772da417fe23f16127edc08d6db7d92e642c965bd5b8634d3a0c963cc97bd4eb295990c8a4fba02929b7657a202c50fa7c93ec093",
          "sha256": "a43b1fb23732a1cb8707aa6801b42ed53aab7cc726a3aa6007175b428d238215",
          "sha1": "3320231d01f3b2acf6975a57dff8e61589ee072a",
          "md5": "d8b3b15afbc92254370f5a34829f665c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 153376,
          "sha512": "b5db57808b8f6ef6a955fb0b2e0b830c9fdbf83b03d317e669303f359066143838b8aec8712b11c80159bbb5a3eaa53dc4376a5bbaa622ce0a24f3de2013d5f3",
          "sha256": "5c0cb9b4e8b6b984407f9a889b6616f97b935be1d564c282a285a36c8b1bd296",
          "sha1": "29479a757a7a9bc82a8f568806a849f8d8725d63",
          "md5": "0fce2bd96ba3c8015e926c77d87fb7e9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-sources.jar",
          "url": "nova-influx-edge-sources.jar",
          "size": 9715,
          "sha512": "8d78a9b2746960bca21098ddd66282f3b84193fb5212428b82a9fe69f1d12cb105270012e3c5f961d01479b01e9854b67457b573a69f8e6a9d2d99d9c1fa3bef",
          "sha256": "b16ccdd51da21c81fff1e42bd3124a83e6074381cef7ce795fa64e852be912f4",
          "sha1": "854dedfab123f924cdb0b8eaf3e46c76dd0613ac",
          "md5": "93f5bb8994ab58f7d4f77b54b0767508"
        }
      ]
    }
  ]
}
