{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45908,
          "sha512": "b772cc1a6a10c920ef87797f9b483ec9101402e5aa895ffbb3e0a68c5ca7feddaa143b62ad612657a007c8c24727310d1b0cccc1e2212f04a914bcfd95d52356",
          "sha256": "3029d75fc59ed4fe2d03a95f97304e48e4ed1c0cdd310c53cc27aba75d95970f",
          "sha1": "1fa61b2ee2f3319f8dadad1e14acb5be6abc31a6",
          "md5": "e711dd04c2423a4860daacc2f4d438e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.5.5"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45908,
          "sha512": "b772cc1a6a10c920ef87797f9b483ec9101402e5aa895ffbb3e0a68c5ca7feddaa143b62ad612657a007c8c24727310d1b0cccc1e2212f04a914bcfd95d52356",
          "sha256": "3029d75fc59ed4fe2d03a95f97304e48e4ed1c0cdd310c53cc27aba75d95970f",
          "sha1": "1fa61b2ee2f3319f8dadad1e14acb5be6abc31a6",
          "md5": "e711dd04c2423a4860daacc2f4d438e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 153376,
          "sha512": "bc331f730456c8087a6de6b3425d1983a3115983201366c6ce5057c878c2e22638571de779355f5a513bb2259698790010769febac265c77bb1ab60cc7dc621a",
          "sha256": "406e74f3db6f0fc7c641ac39af4743cb9a266755a996bc5136e5095e7b31bbe6",
          "sha1": "26a8c0a2c05f5bd80889645c85424963267f958c",
          "md5": "fb06922dfe006e123e0b07928a5ceaf6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-sources.jar",
          "url": "nova-influx-edge-sources.jar",
          "size": 9715,
          "sha512": "37388a53a602efd4473124801250dbaf7a9d60603b299753820617aadca6305b05b83df8c74fb4d1ed14ed6f01871b6a653408b86f953e1f1aa09f8a598f2061",
          "sha256": "f0ba06d532c8d685ec96b3cbce7a983ce1050c7a285787d094415cd4cf6d6726",
          "sha1": "c6293a858b1b7233d647345d38433adcc73ffc87",
          "md5": "3a2bcfea2c20c421752abfb7553a3f33"
        }
      ]
    }
  ]
}
