{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-influx",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45896,
          "sha512": "05fc1118d31f56daa0366f26bd7aa8d810bc0a168d11eda4b57bf47fb22498adfb349503ee248ff06a37fe489db6feddc6878d266bef079d9a4b773304882e26",
          "sha256": "c4e72a3fe6106c8c5681a8f7e995779deda9b238b53297c6bbbc2dcb4b161e62",
          "sha1": "343f2d5a7b3ce809f563fd24982c395002e8e1c5",
          "md5": "c215742410df86bd122f40f410cc63a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-webflux",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-actuator",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-influx-edge.jar",
          "url": "nova-influx-edge.jar",
          "size": 45896,
          "sha512": "05fc1118d31f56daa0366f26bd7aa8d810bc0a168d11eda4b57bf47fb22498adfb349503ee248ff06a37fe489db6feddc6878d266bef079d9a4b773304882e26",
          "sha256": "c4e72a3fe6106c8c5681a8f7e995779deda9b238b53297c6bbbc2dcb4b161e62",
          "sha1": "343f2d5a7b3ce809f563fd24982c395002e8e1c5",
          "md5": "c215742410df86bd122f40f410cc63a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-javadoc.jar",
          "url": "nova-influx-edge-javadoc.jar",
          "size": 153376,
          "sha512": "74d1cb99cfa5710daa0d3edc3d0c14a828cff725e51bfc7f4ff28bcc4330801463138bfea3c67861a76a943231768e9ff3a5280ea2ac22ef5e9b23781a83d72b",
          "sha256": "b003ad5674d18f81271b39f7a5cdf1a15a43cae9fd76b97cece55ba03e6ddc49",
          "sha1": "2efb7b804200fa0084ed2183b0525b9a6e8efd1e",
          "md5": "dc2c822232317a9967f33945ec00cb52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-influx-edge-sources.jar",
          "url": "nova-influx-edge-sources.jar",
          "size": 9715,
          "sha512": "99d3fe3f8de8b3b202bbfbcbcfc7488be2f25f72c3907d8b54e04bd5214e8e882dd1079702cd52e6d50147bef98234c217bb440ab7dfca2f8060c5f7806e0a78",
          "sha256": "89b6e3f61b0b7d52728c679a8928670878fffadb4ada442811063d82ddf9dfa5",
          "sha1": "14a1da0f603c6f5c8e5cede3cd4953251abc690e",
          "md5": "1981853013211135da0ace4bea545f23"
        }
      ]
    }
  ]
}
