{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 45156,
          "sha512": "cf630957da545b540bbb27f65d5a5f8f13e4c4cabf6b7373f734cc15bc6de29c9aff88a0bc7062b9c9606eb156dbaad980425b7c4c0d17e85d0573e5199697ab",
          "sha256": "384df33e1d924a14ca3f88c9ec3893d171fe955b77983f3bb00c65bb0ced3207",
          "sha1": "9d791e9a8f215940026ffc442a6722412680aba3",
          "md5": "267f7b1b149d92abb8e2f25d9a83f598"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.17"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.5.5"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.19.2"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 45156,
          "sha512": "cf630957da545b540bbb27f65d5a5f8f13e4c4cabf6b7373f734cc15bc6de29c9aff88a0bc7062b9c9606eb156dbaad980425b7c4c0d17e85d0573e5199697ab",
          "sha256": "384df33e1d924a14ca3f88c9ec3893d171fe955b77983f3bb00c65bb0ced3207",
          "sha1": "9d791e9a8f215940026ffc442a6722412680aba3",
          "md5": "267f7b1b149d92abb8e2f25d9a83f598"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 187329,
          "sha512": "21d2ec1ebb97742a478f4447016cf322b2267e3de791bbe1e5c716af056a56e10999f41356ebd86a3b063000131e10f815fc519ee68f647a8329850275a04011",
          "sha256": "45c462ebb0b42bc5410c56de2811f210ecbdcff64af8fc3316dd16d787511cd5",
          "sha1": "1eca9c3544b17d31e6380c7341992f745d987836",
          "md5": "5b2c43ae24d48c4a9dd1cd0ab5f365a4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-sources.jar",
          "url": "nova-core-edge-sources.jar",
          "size": 17392,
          "sha512": "39eb2e810502230a0fe6353e1a8916654b83fa058395c1083291622fdecc928fffce79dd197e4838a7b50e410c77506515b0e1a9b9f597da602e8901807bb59a",
          "sha256": "300562410ad6f5324466c1be88b749fe8203e8aeb4730da02282303aa2f72331",
          "sha1": "22fd069ca4f85b444ef23f0a9d0c6a3876bbaec8",
          "md5": "7cbacee1db0929670a0a6ce7361db1b4"
        }
      ]
    }
  ]
}
