{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-core",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 45148,
          "sha512": "1e985bbff887ac179f38973a39ceefe6bab13fd3b1af5789ec7e42d092cabdead0f30fee2fea277b034b41340dd3d257a995aab60673417b98ddcfaf49b43c46",
          "sha256": "2403c6810feaf3a90599e12e5727cfc88397ac174b87533c3a4c3ab02453ca7a",
          "sha1": "d74772650f2340df46c69a402b91dd1b8efd5541",
          "md5": "15eafbcc86ea825fe623034b043d89d5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.15.3"
          }
        }
      ],
      "files": [
        {
          "name": "nova-core-edge.jar",
          "url": "nova-core-edge.jar",
          "size": 45148,
          "sha512": "1e985bbff887ac179f38973a39ceefe6bab13fd3b1af5789ec7e42d092cabdead0f30fee2fea277b034b41340dd3d257a995aab60673417b98ddcfaf49b43c46",
          "sha256": "2403c6810feaf3a90599e12e5727cfc88397ac174b87533c3a4c3ab02453ca7a",
          "sha1": "d74772650f2340df46c69a402b91dd1b8efd5541",
          "md5": "15eafbcc86ea825fe623034b043d89d5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-javadoc.jar",
          "url": "nova-core-edge-javadoc.jar",
          "size": 187311,
          "sha512": "b1fbfee8f762db3f9586917a869568df6da5d9906c9351d51957bdfcdf25b9f8d19633a51a685f2d00867102e28c9169bd20a0acea0ea2ed27f2a9292db4b785",
          "sha256": "b46dcc7327d193e143c5cd3f9aaefcd5b9cebf3502522d48fb15c12b35ef3852",
          "sha1": "e6fa0a1acf0d802a82f07e5027973dcffc74a9d6",
          "md5": "6bcdf1db08453cfb9af4a7f90984d905"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-core-edge-sources.jar",
          "url": "nova-core-edge-sources.jar",
          "size": 17389,
          "sha512": "6eb09ccfb45094ce7fbf1efbcaf803aab0d4421cb87d9eb81ca8d808695ce0ba203517ad54197b13f9945274395a12e171f741ffce921ddeadc6ce877bdd3370",
          "sha256": "490791d016ae35d2b30f22b2ac9c2b4314dc0032213eddf0d0cabbb2ce681269",
          "sha1": "e7217d88af726c18d7cc40d23a0d5bf86510071f",
          "md5": "03624ca208f9c56961a49cbce3e46765"
        }
      ]
    }
  ]
}
