{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16314,
          "sha512": "d1d3684a159bcabd0a20ffcb240b3b7b079e17cb82a261df0735551faa056458d9bebf154312b26ba8799178c9593c7ae1af39580786c9e1ab42f0e24e16fda6",
          "sha256": "91d7401322c40a705d9792f255a067c067a1875d8844d4b93104b3d381487e17",
          "sha1": "0bf8823c9c6080429afb7f87bd8b3d7ad9934e36",
          "md5": "321eb34ca4bfc1b65a03436ab06cdcb2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.4.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16314,
          "sha512": "d1d3684a159bcabd0a20ffcb240b3b7b079e17cb82a261df0735551faa056458d9bebf154312b26ba8799178c9593c7ae1af39580786c9e1ab42f0e24e16fda6",
          "sha256": "91d7401322c40a705d9792f255a067c067a1875d8844d4b93104b3d381487e17",
          "sha1": "0bf8823c9c6080429afb7f87bd8b3d7ad9934e36",
          "md5": "321eb34ca4bfc1b65a03436ab06cdcb2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 98260,
          "sha512": "237e4a9705549a1b59e53b95088fd544ca65f3c2c4075a267f971fb2814867e26c05067ee0fa8836eae1825383a3732087deeb0b89311234f88b55aaebb4b5f5",
          "sha256": "a14ab9e67414bb6dc000dfda5e797abcef7aa308dd45b611ba889640e829392c",
          "sha1": "37459dfd60df1fca0ab98790996130a8c6037931",
          "md5": "46478ec3b2b592cff3020ad537e55f91"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-sources.jar",
          "url": "nova-data-jpa-edge-sources.jar",
          "size": 3460,
          "sha512": "f59bd399454e279b6f59b79f309c23c7e6d1e3d6ea0a0bb3f4ab0e9ff41d064a8bb1d0683ed97472c173fb5d82af70a1aa966d2e7b1b42ea3728a2c25733cce4",
          "sha256": "e862ea5184630aadba2013065ed3d046bdb40a4929f578bc825f8f5ef4e56179",
          "sha1": "318876a91c9776e678651bc5e1c326d0ddf92773",
          "md5": "e2391d1f95a54956b861ac2d4abe972c"
        }
      ]
    }
  ]
}
