{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16315,
          "sha512": "a481cd5952348fc5c8a473da271a7c8a64178642198950674061f2c9a7ecb03c5a07be0a3fac164fc348511edbe1c96be5e40d063e4c487c1ea5c88c549fba5e",
          "sha256": "bc58cb3341389ccff48fdb2f7f453bbb57c7c5a10bc3324bc2a0fa23a3ddd027",
          "sha1": "a5f7b2ec14a77e03853c328220e22ee182b8203a",
          "md5": "d2b4e442f78a0263918e7b16199319e7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.4.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16315,
          "sha512": "a481cd5952348fc5c8a473da271a7c8a64178642198950674061f2c9a7ecb03c5a07be0a3fac164fc348511edbe1c96be5e40d063e4c487c1ea5c88c549fba5e",
          "sha256": "bc58cb3341389ccff48fdb2f7f453bbb57c7c5a10bc3324bc2a0fa23a3ddd027",
          "sha1": "a5f7b2ec14a77e03853c328220e22ee182b8203a",
          "md5": "d2b4e442f78a0263918e7b16199319e7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 98262,
          "sha512": "7f30d325b922df7074ef5d5433a8d2f3d144601450a0a4672a45816a404de76c8e520b3942b1d16734b7e4e90fe05e7bc1e072eda2ce579b128c888113534d41",
          "sha256": "8dc56ad7270a9e6ee2cd99360d357880a4a466520e3c761ea1cb4e329488ef10",
          "sha1": "ee1ba548c15049c3e350114d990e4607542dc971",
          "md5": "4cbb48875ab65bdb695307c8bab5a99f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-sources.jar",
          "url": "nova-data-jpa-edge-sources.jar",
          "size": 3462,
          "sha512": "bbe4d2f46cf727ae170468c94cd3fb5a20df61f42b49b320d30d696b0bcb636d3b9459cb2f56e518edb55cc2bcdf36fde8e24858b60b3959d6fb2afca1d917ce",
          "sha256": "997911982e7b3761b97c39ab981d7d7a2615885e3f4d6a27b55f3822433b7642",
          "sha1": "86f051ea96595341615631aa4981589b4a8cb668",
          "md5": "73daf7d2317051df64fd71f2cfa0310c"
        }
      ]
    }
  ]
}
