{
  "formatVersion": "1.1",
  "component": {
    "group": "de.m4rc3l.nova",
    "module": "nova-data-jpa",
    "version": "edge",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16316,
          "sha512": "3e50c37485862a5eaa277a1903d68c3585ee6fe4307a5d6f4d4509acaeb870f28ae6837efe1acbf84a7d8027b5e19a4f70eee53fb7280a3ad9711e348f0b71e8",
          "sha256": "a0fde7fccb6d080f377fc33bd6a5ad41dd2baf98767850b5948e763fd135e559",
          "sha1": "c71c96bff731f647baa2e68518a30ca23a01ad9b",
          "md5": "faa73fd84f86b7f813aa2616f32540b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "2.0.9"
          }
        },
        {
          "group": "org.hibernate.orm",
          "module": "hibernate-core",
          "version": {
            "requires": "6.4.4.Final"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "nova-data-jpa-edge.jar",
          "url": "nova-data-jpa-edge.jar",
          "size": 16316,
          "sha512": "3e50c37485862a5eaa277a1903d68c3585ee6fe4307a5d6f4d4509acaeb870f28ae6837efe1acbf84a7d8027b5e19a4f70eee53fb7280a3ad9711e348f0b71e8",
          "sha256": "a0fde7fccb6d080f377fc33bd6a5ad41dd2baf98767850b5948e763fd135e559",
          "sha1": "c71c96bff731f647baa2e68518a30ca23a01ad9b",
          "md5": "faa73fd84f86b7f813aa2616f32540b6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-javadoc.jar",
          "url": "nova-data-jpa-edge-javadoc.jar",
          "size": 98262,
          "sha512": "a66d4f75cf3790e0e1d7adc732b2b14fd58c5b6c32346c65f47afd22a0f1c73bb39e60195787707359363ddfa2f96844ae8fd2ef857a2ec8b54388a13266bd80",
          "sha256": "696f6fa3c18288ba384a68f987b8c298ac7c564b519890df912b48abbd6dd075",
          "sha1": "2988c6533d5d355465d9727c690abcbbeb41c46b",
          "md5": "e0133bf3a1278c4851c480164c2ffd57"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nova-data-jpa-edge-sources.jar",
          "url": "nova-data-jpa-edge-sources.jar",
          "size": 3462,
          "sha512": "5c2ccc416125cf0ebd884b24b7d58d8ae4e38cb4fcce00e5367b490aa7c1534765bc7f92e14cb57d1781b3a8d2cf8d53971c2a3c5ba712d8e376f75f62cca867",
          "sha256": "d834649292245925dc5e671b919756941f2f27f7d8e0ea9d6e50aa419ccdc981",
          "sha1": "f31d8383fd37d4dc473f8e8314955f2df51e4271",
          "md5": "f063323f62f3b1cc8efe3083768fec29"
        }
      ]
    }
  ]
}
